Feature/LS-2 進度報告頁面改善
Lidemy/lidemy-learning-frontend pull request #3
Opened 2020-04-03 06:40 UTC by ishin4554

新增顯示發文者角色與 SlackId 並支持 Highlight Codeblock
ticket LS-7, LS-8, LS-9

2020-04-03 12:02 UTC, aszx87410 commented on package.json
> +    "firebase": "^7.13.1",
哇，一下升了兩個版本
可以幫我確認一下登入功能都安好嗎？感恩

2020-04-03 12:04 UTC, aszx87410 commented on src/components/editor/editor.js
> +            <ReactMarkdown source={value} renderers={{ code: CodeBlock }} />
這邊可以順便重構一下，因為你會發現我在程式碼裡面用了很多次 `ReactMarkdown`，但其實應該包成一個
可以在 components 資料夾裡面直接新增一個 common 的資料夾， 再新增一個 `Markdown` 的 component，把這段包起來，然後把所有用到 ReactMarkdown 的 component 都改用這個

2020-04-03 12:06 UTC, aszx87410 requested changes
把 Markdown 那個重構一下應該就差不多了

2020-04-03 14:10 UTC, ishin4554 commented on package.json
> +    "firebase": "^7.13.1",
原本 5.9.1 升級 7.13.1 是因為 npm 顯示大量 fsevent ERR 所以升級，
7.13.1 的第三方登入沒有問題，但剛剛測試 5.9.1 雖然會顯示 ERR 但依舊可以運行，
要降回 5.9.1 嗎？

2020-04-03 14:11 UTC, ishin4554 commented on src/components/editor/editor.js
> +            <ReactMarkdown source={value} renderers={{ code: CodeBlock }} />
OK，沒有問題！

2020-04-03 14:15 UTC, aszx87410 commented on package.json
> +    "firebase": "^7.13.1",
7.13.1 沒問題的話那就升上去好了

2020-04-04 15:19 UTC, ishin4554 commented
> 把 Markdown 那個重構一下應該就差不多了
@aszx87410 重構完成～

2020-04-04 15:43 UTC, aszx87410 commented on src/components/editor/editor.js
> +            <Markdown source={value} linkTarget="_blank" />
linkTarget 看起來沒傳進去，因為 Markdown 只吃一個 source

2020-04-04 15:44 UTC, aszx87410 commented on src/components/editor/editor.js
> +            <Markdown source={value} linkTarget="_blank" />
然後其實這邊可以不用傳，然後 Markdown 的 linkTarget default 就設定成 _blank
預設就開新視窗比較好

2020-04-04 15:44 UTC, aszx87410 commented on src/components/common/markdown.js
> +  <ReactMarkdown source={source} renderers={{ code: CodeBlock }} />
加個 linkTarget="_blank"

2020-04-04 16:27 UTC, ishin4554 commented
@aszx87410 這邊 linkTarget="_blank" 調整完成～ 麻煩了。

2020-04-04 16:34 UTC, merged